In [68]:
import time 
start_time = time.time()

In [69]:
import pandas as pd
import numpy as np
import tensorflow as tf
tf.__version__

'2.13.0'

In [70]:
df = pd.read_csv("datasets/Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [71]:
x = df.iloc[:,3:-1]
y = df.iloc[:,-1].values

In [72]:
print(x)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0           

In [73]:
x = pd.get_dummies(x,columns=['Geography','Gender']).values

In [74]:
print(x)

[[619.  42.   2. ...   0.   1.   0.]
 [608.  41.   1. ...   1.   1.   0.]
 [502.  42.   8. ...   0.   1.   0.]
 ...
 [709.  36.   7. ...   0.   1.   0.]
 [772.  42.   3. ...   0.   0.   1.]
 [792.  28.   4. ...   0.   1.   0.]]


In [75]:
print(y)

[1 0 1 ... 1 1 0]


In [76]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [77]:
print(x_train)

[[667.  34.   5. ...   1.   1.   0.]
 [427.  42.   1. ...   0.   0.   1.]
 [535.  29.   2. ...   0.   1.   0.]
 ...
 [738.  35.   5. ...   0.   0.   1.]
 [590.  38.   9. ...   1.   1.   0.]
 [623.  48.   1. ...   0.   1.   0.]]


In [78]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [79]:
print(x_train)

[[ 0.16958176 -0.46460796  0.00666099 ...  1.74309049  1.09168714
  -1.09168714]
 [-2.30455945  0.30102557 -1.37744033 ... -0.57369368 -0.91601335
   0.91601335]
 [-1.19119591 -0.94312892 -1.031415   ... -0.57369368  1.09168714
  -1.09168714]
 ...
 [ 0.9015152  -0.36890377  0.00666099 ... -0.57369368 -0.91601335
   0.91601335]
 [-0.62420521 -0.08179119  1.39076231 ...  1.74309049  1.09168714
  -1.09168714]
 [-0.28401079  0.87525072 -1.37744033 ... -0.57369368  1.09168714
  -1.09168714]]


In [80]:
ann = tf.keras.models.Sequential()

In [81]:
ann.add(tf.keras.layers.Dense(units=8,activation='relu'))

In [82]:
ann.add(tf.keras.layers.Dense(units=7,activation='relu'))


In [83]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [84]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [85]:
ann.compile(optimizer="adam",loss='binary_crossentropy',metrics = ['accuracy'])

In [86]:
# tb_callback = tf.keras.callbacks.TensorBoard(log_dir="logs/")
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100


250/250 [==============================] - 1s 2ms/step - loss: 0.6597 - accuracy: 0.6024
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4507 - accuracy: 0.8066
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4152 - accuracy: 0.8185
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3974 - accuracy: 0.8298
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3807 - accuracy: 0.8411
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3653 - accuracy: 0.8485
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3564 - accuracy: 0.8518
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3518 - accuracy: 0.8540
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3477 - accuracy: 0.8569
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3457 - accuracy: 0.8583
E

In [87]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [88]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1523   72]
 [ 212  193]]


0.858

In [89]:
end_time = time.time()
elapsed_time = end_time - start_time
print(elapsed_time)

39.9117636680603


In [90]:
# with cpu -> 21.18 sec, 29.07 sec
# with gpu -> 61.21 sec, 73.78 sec